apiVersion: apps/v1
kind: Deployment
metadata:
  name: account-service
  namespace: lovable-core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: account-service
  template:
    metadata:
      labels:
        app:  account-service
    spec:
      containers:
      - name: account-service
        image: rahulmahalwaar/lovable-account-service:0.0.1
        imagePullPolicy: Always

        env:
          - name: SPRING_PROFILES_ACTIVE
            value: k8s
          - name: CONFIG_SERVER_URL
            value: http://config-service.lovable-core.svc.cluster.local:8888
          - name: SPRING_CLOUD_CONFIG_FAIL_FAST
            value: "false"
          - name:  SPRING_CLOUD_CONFIG_RETRY_MAX_ATTEMPTS
            value: "10"
          - name: SPRING_CLOUD_CONFIG_RETRY_INITIAL_INTERVAL
            value: "3000"
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: ACCOUNT_DB_PASSWORD
          - name: JWT_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: JWT_SECRET
          - name: RAZORPAY_WEBHOOK_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: RAZORPAY_WEBHOOK_SECRET
          - name: RAZORPAY_KEY_ID
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: RAZORPAY_KEY_ID
          - name: RAZORPAY_KEY_SECRET
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: RAZORPAY_KEY_SECRET
          - name: FRONTEND_URL
            value: "http://my-lovable.in"
        ports:
          - containerPort: 9050
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        readinessProbe:
          httpGet:
            path: /account/actuator/health
            port: 9050
          initialDelaySeconds: 90
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /account/actuator/health
            port: 9050
          initialDelaySeconds: 90
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 30
          


---
apiVersion: v1
kind: Service
metadata:
  name: account-service
  namespace: lovable-core
spec:
  selector:
    app: account-service
  ports:
  - port: 80
    targetPort: 9050

